# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.URLField(unique=True)),
                ('is_private', models.BooleanField()),
            ],
        ),
    ]
